import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import LanguagePicker from '../components/languagePicker'
import { useTranslations } from 'next-intl'
import Authorisation from '../components/authorisation'
import { withPageAuthRequired } from '@auth0/nextjs-auth0';

export default function Home() {

  const t = useTranslations('Translations');

  return (
    <div className={styles.container}>

      <Head>
        <title>{t('create')}</title>
        <meta name="description" content="Not Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Authorisation />
        <LanguagePicker />
        <h1 className={styles.title}>
        {t('welcome')} <a href="https://nextjs.org">Next.js! {t('protectedTitle')}</a>
        </h1>

        <p className={styles.description}>
        {t('started')}
          <code className={styles.code}>pages/index.js</code>
          <Link href="/">
            <a>{t('indexPage')}</a>
        </Link>
        </p>
      </main>

    </div>
  )
}

export const getServerSideProps = (ctx) => {
  // the ctx locale will be extracted in the login function for the auth0 language paramater needed  
  const returnTo = `${process.env.AUTH0_BASE_URL}/${ctx.locale}${ctx.resolvedUrl}`;
  return withPageAuthRequired({ returnTo, async getServerSideProps(ctx) {
    return {
      props: {
        messages: (await import(`../messages/${ctx.locale}.json`)).default,
      },
    };
  }, })(ctx);
};